application: budget-hr
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: handlers.home.app
  login: required

- url: /data(/.*)?
  script: handlers.data.app
  login: admin

- url: /build
  static_dir: build
  login: required
